Repository CMU-313/fall22-hw3-team-lantern-exchange, pull requests merged in 2022-10, with the labels that each got.

#10 added new api call and modified current calls to allow admins to rate…
  docs-core/src/main/java/com/sismics/docs/core/event/DocumentRatedAsyncEvent.java
  docs-web/src/main/java/com/sismics/docs/rest/resource/DocumentResource.java
Labels: Middleware

#13 Added documentation notes file
  README.md
  teamLanternExchangeDocumentation
Labels: documentation

#14 Updated document-related classes and database in backend
  docs-core/src/main/java/com/sismics/docs/core/dao/DocumentDao.java
  docs-core/src/main/java/com/sismics/docs/core/dao/dto/DocumentDto.java
  docs-core/src/main/java/com/sismics/docs/core/model/jpa/Document.java
  docs-core/src/main/resources/config.properties
  docs-core/src/main/resources/db/update/dbupdate-028-0.sql
  docs-web/src/dev/resources/config.properties
  docs-web/src/prod/resources/config.properties
Labels: Backend

#11 unit testing and backend connection fixes for middleware
  docs-web/src/main/java/com/sismics/docs/rest/resource/DocumentResource.java
  docs-web/src/test/java/com/sismics/docs/rest/TestDocumentResource.java
Labels: Middleware

#15 Add unit tests for backend
  docs-core/src/test/java/com/sismics/docs/core/dao/TestDocument.java
Labels: Backend
